//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int ReferenceId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Alias { get; set; }
        public string Email { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
